export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS"



export const GET_FILMS_LIST_SUCCESS = "GET_FILMS_LIST_SUCCESS"
export const GET_FILMS_LIST_FAILURE = "GET_FILMS_LIST_FAILURE"

